audioFrameLimit = false
autoBackup = true
autoFindMic = false
branch = 'release'
cachePath = 'C:\Games\MAJESTIC_GTA\cache'
cefAlwaysFullCopy = false
cefUseHardwareAcceleration = true
consoleHeight = 0.40000000596046448
consoleWidth = 0.40000000596046448
crashOnFatalError = false
crashReporterEnabled = true
debug = false
disableForcedRawInput = false
disableRtl = false
discordRichPresence = false
displaySystemUpdateMessagesInLog = false
earlyAuthTestURL = ''
enableDiscordOverlay = true
enableGuildedOverlay = false
enableModDirectory = true
enableNvidiaShadowPlayOverlay = true
enableOverwolfOverlay = false
expandedConsole = true
externalConsoleX = 0
externalConsoleY = 0
gameTimeout = 120
gtaPlatform = 'steam'
gtapath = 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V'
heapSize = 1024
lang = 'ru'
launcherSkin = 'm8y0hmp'
launcherSkinsDisabled = []
linuxCompatibility = false
logTimeFormat = '%H:%M:%S'
maxDownloadSpeed = 0
name = 'MajesticPlayer'
netgraph = false
permissionsSet = true
region = 'global'
streamerMode = false
textureBudgetPatch = true
uiVolume = 50
useExternalConsole = false
useSharedTextures = false
voiceActivationEnabled = false
voiceActivationKey = 78
voiceAutoInputVolume = true
voiceEnabled = true
voiceInputDevice = '{0.0.1.00000000}.{9cc2acde-b0d8-4aeb-a473-44cef351429d}'
voiceInputNormalization = true
voiceInputSensitivity = 20
voiceInputVolume = 100
voiceNoiseSuppression = false
voiceVolume = 200